// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: feather/v1/flag.proto

package flagv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_feather_v1_flag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LogInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInRequest) Reset() {
	*x = LogInRequest{}
	mi := &file_feather_v1_flag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInRequest) ProtoMessage() {}

func (x *LogInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInRequest.ProtoReflect.Descriptor instead.
func (*LogInRequest) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{1}
}

func (x *LogInRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LogInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SdkKey        string                 `protobuf:"bytes,3,opt,name=sdk_key,json=sdkKey,proto3" json:"sdk_key,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_feather_v1_flag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetSdkKey() string {
	if x != nil {
		return x.SdkKey
	}
	return ""
}

func (x *AuthResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_feather_v1_flag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_feather_v1_flag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Flag struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Key               string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Enabled           bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RolloutPercentage uint32                 `protobuf:"varint,4,opt,name=rollout_percentage,json=rolloutPercentage,proto3" json:"rollout_percentage,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_feather_v1_flag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{5}
}

func (x *Flag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Flag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flag) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Flag) GetRolloutPercentage() uint32 {
	if x != nil {
		return x.RolloutPercentage
	}
	return 0
}

func (x *Flag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Flag) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateFlagRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Key               string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Enabled           bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RolloutPercentage uint32                 `protobuf:"varint,4,opt,name=rollout_percentage,json=rolloutPercentage,proto3" json:"rollout_percentage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateFlagRequest) Reset() {
	*x = CreateFlagRequest{}
	mi := &file_feather_v1_flag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlagRequest) ProtoMessage() {}

func (x *CreateFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlagRequest.ProtoReflect.Descriptor instead.
func (*CreateFlagRequest) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{6}
}

func (x *CreateFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateFlagRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFlagRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CreateFlagRequest) GetRolloutPercentage() uint32 {
	if x != nil {
		return x.RolloutPercentage
	}
	return 0
}

type ToggleFlagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFlagRequest) Reset() {
	*x = ToggleFlagRequest{}
	mi := &file_feather_v1_flag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFlagRequest) ProtoMessage() {}

func (x *ToggleFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFlagRequest.ProtoReflect.Descriptor instead.
func (*ToggleFlagRequest) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{7}
}

func (x *ToggleFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ToggleFlagRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdateRolloutRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Key               string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RolloutPercentage uint32                 `protobuf:"varint,2,opt,name=rollout_percentage,json=rolloutPercentage,proto3" json:"rollout_percentage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateRolloutRequest) Reset() {
	*x = UpdateRolloutRequest{}
	mi := &file_feather_v1_flag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRolloutRequest) ProtoMessage() {}

func (x *UpdateRolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRolloutRequest.ProtoReflect.Descriptor instead.
func (*UpdateRolloutRequest) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRolloutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateRolloutRequest) GetRolloutPercentage() uint32 {
	if x != nil {
		return x.RolloutPercentage
	}
	return 0
}

type ListFlagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlagsRequest) Reset() {
	*x = ListFlagsRequest{}
	mi := &file_feather_v1_flag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlagsRequest) ProtoMessage() {}

func (x *ListFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlagsRequest.ProtoReflect.Descriptor instead.
func (*ListFlagsRequest) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{9}
}

type ListFlagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         []*Flag                `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlagsResponse) Reset() {
	*x = ListFlagsResponse{}
	mi := &file_feather_v1_flag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlagsResponse) ProtoMessage() {}

func (x *ListFlagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlagsResponse.ProtoReflect.Descriptor instead.
func (*ListFlagsResponse) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{10}
}

func (x *ListFlagsResponse) GetFlags() []*Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

type DeleteFlagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFlagRequest) Reset() {
	*x = DeleteFlagRequest{}
	mi := &file_feather_v1_flag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlagRequest) ProtoMessage() {}

func (x *DeleteFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlagRequest.ProtoReflect.Descriptor instead.
func (*DeleteFlagRequest) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteFlagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFlagResponse) Reset() {
	*x = DeleteFlagResponse{}
	mi := &file_feather_v1_flag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlagResponse) ProtoMessage() {}

func (x *DeleteFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlagResponse.ProtoReflect.Descriptor instead.
func (*DeleteFlagResponse) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteFlagResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ContextKey    string                 `protobuf:"bytes,2,opt,name=context_key,json=contextKey,proto3" json:"context_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_feather_v1_flag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{13}
}

func (x *EvaluateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EvaluateRequest) GetContextKey() string {
	if x != nil {
		return x.ContextKey
	}
	return ""
}

type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_feather_v1_flag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feather_v1_flag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_feather_v1_flag_proto_rawDescGZIP(), []int{14}
}

func (x *EvaluateResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EvaluateResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_feather_v1_flag_proto protoreflect.FileDescriptor

const file_feather_v1_flag_proto_rawDesc = "" +
	"\n" +
	"\x15feather/v1/flag.proto\x12\n" +
	"feather.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n" +
	"\rSignUpRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"@\n" +
	"\fLogInRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x9e\x01\n" +
	"\fAuthResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\asdk_key\x18\x03 \x01(\tR\x06sdkKey\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"9\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"F\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xf9\x01\n" +
	"\x04Flag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12-\n" +
	"\x12rollout_percentage\x18\x04 \x01(\rR\x11rolloutPercentage\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x90\x01\n" +
	"\x11CreateFlagRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12-\n" +
	"\x12rollout_percentage\x18\x04 \x01(\rR\x11rolloutPercentage\"?\n" +
	"\x11ToggleFlagRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"W\n" +
	"\x14UpdateRolloutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x12rollout_percentage\x18\x02 \x01(\rR\x11rolloutPercentage\"\x12\n" +
	"\x10ListFlagsRequest\";\n" +
	"\x11ListFlagsResponse\x12&\n" +
	"\x05flags\x18\x01 \x03(\v2\x10.feather.v1.FlagR\x05flags\"%\n" +
	"\x11DeleteFlagRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\".\n" +
	"\x12DeleteFlagResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"D\n" +
	"\x0fEvaluateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\vcontext_key\x18\x02 \x01(\tR\n" +
	"contextKey\"D\n" +
	"\x10EvaluateResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xdf\x01\n" +
	"\vAuthService\x12=\n" +
	"\x06SignUp\x12\x19.feather.v1.SignUpRequest\x1a\x18.feather.v1.AuthResponse\x12;\n" +
	"\x05LogIn\x12\x18.feather.v1.LogInRequest\x1a\x18.feather.v1.AuthResponse\x12T\n" +
	"\rValidateToken\x12 .feather.v1.ValidateTokenRequest\x1a!.feather.v1.ValidateTokenResponse2\xae\x03\n" +
	"\vFlagService\x12=\n" +
	"\n" +
	"CreateFlag\x12\x1d.feather.v1.CreateFlagRequest\x1a\x10.feather.v1.Flag\x12=\n" +
	"\n" +
	"ToggleFlag\x12\x1d.feather.v1.ToggleFlagRequest\x1a\x10.feather.v1.Flag\x12C\n" +
	"\rUpdateRollout\x12 .feather.v1.UpdateRolloutRequest\x1a\x10.feather.v1.Flag\x12H\n" +
	"\tListFlags\x12\x1c.feather.v1.ListFlagsRequest\x1a\x1d.feather.v1.ListFlagsResponse\x12K\n" +
	"\n" +
	"DeleteFlag\x12\x1d.feather.v1.DeleteFlagRequest\x1a\x1e.feather.v1.DeleteFlagResponse\x12E\n" +
	"\bEvaluate\x12\x1b.feather.v1.EvaluateRequest\x1a\x1c.feather.v1.EvaluateResponseB4Z2github.com/Bethel-nz/feather/gen/feather/v1;flagv1b\x06proto3"

var (
	file_feather_v1_flag_proto_rawDescOnce sync.Once
	file_feather_v1_flag_proto_rawDescData []byte
)

func file_feather_v1_flag_proto_rawDescGZIP() []byte {
	file_feather_v1_flag_proto_rawDescOnce.Do(func() {
		file_feather_v1_flag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feather_v1_flag_proto_rawDesc), len(file_feather_v1_flag_proto_rawDesc)))
	})
	return file_feather_v1_flag_proto_rawDescData
}

var file_feather_v1_flag_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_feather_v1_flag_proto_goTypes = []any{
	(*SignUpRequest)(nil),         // 0: feather.v1.SignUpRequest
	(*LogInRequest)(nil),          // 1: feather.v1.LogInRequest
	(*AuthResponse)(nil),          // 2: feather.v1.AuthResponse
	(*ValidateTokenRequest)(nil),  // 3: feather.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 4: feather.v1.ValidateTokenResponse
	(*Flag)(nil),                  // 5: feather.v1.Flag
	(*CreateFlagRequest)(nil),     // 6: feather.v1.CreateFlagRequest
	(*ToggleFlagRequest)(nil),     // 7: feather.v1.ToggleFlagRequest
	(*UpdateRolloutRequest)(nil),  // 8: feather.v1.UpdateRolloutRequest
	(*ListFlagsRequest)(nil),      // 9: feather.v1.ListFlagsRequest
	(*ListFlagsResponse)(nil),     // 10: feather.v1.ListFlagsResponse
	(*DeleteFlagRequest)(nil),     // 11: feather.v1.DeleteFlagRequest
	(*DeleteFlagResponse)(nil),    // 12: feather.v1.DeleteFlagResponse
	(*EvaluateRequest)(nil),       // 13: feather.v1.EvaluateRequest
	(*EvaluateResponse)(nil),      // 14: feather.v1.EvaluateResponse
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_feather_v1_flag_proto_depIdxs = []int32{
	15, // 0: feather.v1.AuthResponse.expires_at:type_name -> google.protobuf.Timestamp
	15, // 1: feather.v1.Flag.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: feather.v1.Flag.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 3: feather.v1.ListFlagsResponse.flags:type_name -> feather.v1.Flag
	0,  // 4: feather.v1.AuthService.SignUp:input_type -> feather.v1.SignUpRequest
	1,  // 5: feather.v1.AuthService.LogIn:input_type -> feather.v1.LogInRequest
	3,  // 6: feather.v1.AuthService.ValidateToken:input_type -> feather.v1.ValidateTokenRequest
	6,  // 7: feather.v1.FlagService.CreateFlag:input_type -> feather.v1.CreateFlagRequest
	7,  // 8: feather.v1.FlagService.ToggleFlag:input_type -> feather.v1.ToggleFlagRequest
	8,  // 9: feather.v1.FlagService.UpdateRollout:input_type -> feather.v1.UpdateRolloutRequest
	9,  // 10: feather.v1.FlagService.ListFlags:input_type -> feather.v1.ListFlagsRequest
	11, // 11: feather.v1.FlagService.DeleteFlag:input_type -> feather.v1.DeleteFlagRequest
	13, // 12: feather.v1.FlagService.Evaluate:input_type -> feather.v1.EvaluateRequest
	2,  // 13: feather.v1.AuthService.SignUp:output_type -> feather.v1.AuthResponse
	2,  // 14: feather.v1.AuthService.LogIn:output_type -> feather.v1.AuthResponse
	4,  // 15: feather.v1.AuthService.ValidateToken:output_type -> feather.v1.ValidateTokenResponse
	5,  // 16: feather.v1.FlagService.CreateFlag:output_type -> feather.v1.Flag
	5,  // 17: feather.v1.FlagService.ToggleFlag:output_type -> feather.v1.Flag
	5,  // 18: feather.v1.FlagService.UpdateRollout:output_type -> feather.v1.Flag
	10, // 19: feather.v1.FlagService.ListFlags:output_type -> feather.v1.ListFlagsResponse
	12, // 20: feather.v1.FlagService.DeleteFlag:output_type -> feather.v1.DeleteFlagResponse
	14, // 21: feather.v1.FlagService.Evaluate:output_type -> feather.v1.EvaluateResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_feather_v1_flag_proto_init() }
func file_feather_v1_flag_proto_init() {
	if File_feather_v1_flag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feather_v1_flag_proto_rawDesc), len(file_feather_v1_flag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_feather_v1_flag_proto_goTypes,
		DependencyIndexes: file_feather_v1_flag_proto_depIdxs,
		MessageInfos:      file_feather_v1_flag_proto_msgTypes,
	}.Build()
	File_feather_v1_flag_proto = out.File
	file_feather_v1_flag_proto_goTypes = nil
	file_feather_v1_flag_proto_depIdxs = nil
}
