// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Flag struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	Key               string
	Description       string
	Enabled           bool
	RolloutPercentage int16
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Project struct {
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
	Name       string
	SdkKeyHash string
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
