// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlag = `-- name: CreateFlag :one
INSERT INTO flags (project_id, key, description, enabled, rollout_percentage)
VALUES ($1, $2, $3, $4, $5) RETURNING id, project_id, key, description, enabled, rollout_percentage, created_at, updated_at
`

type CreateFlagParams struct {
	ProjectID         pgtype.UUID
	Key               string
	Description       string
	Enabled           bool
	RolloutPercentage int16
}

func (q *Queries) CreateFlag(ctx context.Context, arg CreateFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, createFlag,
		arg.ProjectID,
		arg.Key,
		arg.Description,
		arg.Enabled,
		arg.RolloutPercentage,
	)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Description,
		&i.Enabled,
		&i.RolloutPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (owner_id, name, sdk_key_hash) VALUES ($1, $2, $3)
`

type CreateProjectParams struct {
	OwnerID    pgtype.UUID
	Name       string
	SdkKeyHash string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject, arg.OwnerID, arg.Name, arg.SdkKeyHash)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash) VALUES ($1, $2) RETURNING id, email, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const deleteFlagByKey = `-- name: DeleteFlagByKey :execrows
DELETE FROM flags WHERE project_id = $1 AND key = $2
`

type DeleteFlagByKeyParams struct {
	ProjectID pgtype.UUID
	Key       string
}

func (q *Queries) DeleteFlagByKey(ctx context.Context, arg DeleteFlagByKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFlagByKey, arg.ProjectID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFirstProject = `-- name: GetFirstProject :one
SELECT id, owner_id, name, sdk_key_hash, created_at FROM projects ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) GetFirstProject(ctx context.Context) (Project, error) {
	row := q.db.QueryRow(ctx, getFirstProject)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.SdkKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getFlagByKey = `-- name: GetFlagByKey :one
SELECT id, project_id, key, description, enabled, rollout_percentage, created_at, updated_at FROM flags WHERE project_id = $1 AND key = $2
`

type GetFlagByKeyParams struct {
	ProjectID pgtype.UUID
	Key       string
}

func (q *Queries) GetFlagByKey(ctx context.Context, arg GetFlagByKeyParams) (Flag, error) {
	row := q.db.QueryRow(ctx, getFlagByKey, arg.ProjectID, arg.Key)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Description,
		&i.Enabled,
		&i.RolloutPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByOwnerID = `-- name: GetProjectByOwnerID :one
SELECT id, owner_id, name, sdk_key_hash, created_at FROM projects WHERE owner_id = $1
`

func (q *Queries) GetProjectByOwnerID(ctx context.Context, ownerID pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByOwnerID, ownerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.SdkKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectBySDKKeyHash = `-- name: GetProjectBySDKKeyHash :one
SELECT id, owner_id, name, sdk_key_hash, created_at FROM projects WHERE sdk_key_hash = $1
`

func (q *Queries) GetProjectBySDKKeyHash(ctx context.Context, sdkKeyHash string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySDKKeyHash, sdkKeyHash)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.SdkKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listFlagsByProject = `-- name: ListFlagsByProject :many
SELECT id, project_id, key, description, enabled, rollout_percentage, created_at, updated_at FROM flags WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListFlagsByProject(ctx context.Context, projectID pgtype.UUID) ([]Flag, error) {
	rows, err := q.db.Query(ctx, listFlagsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Description,
			&i.Enabled,
			&i.RolloutPercentage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlagEnabled = `-- name: UpdateFlagEnabled :one
UPDATE flags SET enabled = $1, updated_at = now() WHERE project_id = $2 AND key = $3 RETURNING id, project_id, key, description, enabled, rollout_percentage, created_at, updated_at
`

type UpdateFlagEnabledParams struct {
	Enabled   bool
	ProjectID pgtype.UUID
	Key       string
}

func (q *Queries) UpdateFlagEnabled(ctx context.Context, arg UpdateFlagEnabledParams) (Flag, error) {
	row := q.db.QueryRow(ctx, updateFlagEnabled, arg.Enabled, arg.ProjectID, arg.Key)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Description,
		&i.Enabled,
		&i.RolloutPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlagRollout = `-- name: UpdateFlagRollout :one
UPDATE flags SET rollout_percentage = $1, updated_at = now() WHERE project_id = $2 AND key = $3 RETURNING id, project_id, key, description, enabled, rollout_percentage, created_at, updated_at
`

type UpdateFlagRolloutParams struct {
	RolloutPercentage int16
	ProjectID         pgtype.UUID
	Key               string
}

func (q *Queries) UpdateFlagRollout(ctx context.Context, arg UpdateFlagRolloutParams) (Flag, error) {
	row := q.db.QueryRow(ctx, updateFlagRollout, arg.RolloutPercentage, arg.ProjectID, arg.Key)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Description,
		&i.Enabled,
		&i.RolloutPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectSDKKey = `-- name: UpdateProjectSDKKey :exec
UPDATE projects SET sdk_key_hash = $1 WHERE id = $2
`

type UpdateProjectSDKKeyParams struct {
	SdkKeyHash string
	ID         pgtype.UUID
}

func (q *Queries) UpdateProjectSDKKey(ctx context.Context, arg UpdateProjectSDKKeyParams) error {
	_, err := q.db.Exec(ctx, updateProjectSDKKey, arg.SdkKeyHash, arg.ID)
	return err
}
